routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MasyarakatController;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', function () {
    return view('dashboard');

})->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/daftarLaporan', [AdminController::class, 'index'])->middleware(['auth', 'verified'])->name('daftarLaporan');

Route::get('/buatLaporan', function () {
    return view('buatLaporan');
})->middleware(['auth', 'verified'])->name('buatLaporan');

Route::resource('/tanggapan', AdminController::class)->middleware(['auth', 'verified']);

Route::get('/riwayatLaporan', [MasyarakatController::class, 'index',])->middleware(['auth', 'verified'])->name('riwayatLaporan');


// Route::middleware(['auth','verified', 'checkRole:Administrator'])->group(function () {
//     // Route::post('/buatLaporan', [MasyarakatController::class, 'store'])->name('masyarakat.store');
//     Route::resource('masyarakat', MasyarakatController::class);
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

Route::middleware('auth')->group (function () {
    Route::get('/admin/pdf', [AdminController::class, 'createPDF']);

    // Route::post('/buatLaporan', [MasyarakatController::class, 'store'])->name('masyarakat.store');
    Route::resource('masyarakat', MasyarakatController::class);
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::put('proses/{id}', [AdminController::class, 'update'])->name('proses');
    Route::put('selesai/{id}', [AdminController::class, 'selesai'])->name('selesai');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/buatLaporan.blade.php
<x-app-layout class="">
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          Selamat Datang Di Dashboard Pengaduan Masyarakat Desa Komba
        </h2>
    </x-slot>

    <div class="container rounded bg-light  shadow-lg mt-3 mb-3" >
      
<form class="mt-5" method="POST" action="{{ route('masyarakat.store') }}" enctype="multipart/form-data">
  @csrf
  @method('POST')
    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nama Pengadu</label>
    <input type="text" class="form-control rounded border-secondary border" name="nama_pengadu" value={{Auth::user()->name}} id="exampleInputEmail1" aria-describedby="emailHelp" disabled>
    {{-- <input type="hidden" class="form-control rounded border-secondary border" name="nik" value={{Auth::user()->nik}} id="exampleInputEmail1" aria-describedby="emailHelp" disabled> --}}
    <div id="emailHelp" class="form-text"></div>
  

  <div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Jelaskan Masalah</label>
  <textarea class="form-control rounded border-secondary border" name="isi_laporan" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>

  <div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Tanggal</label>
  <input type="date" class="form-control rounded border-secondary border" name="tgl_pengaduan" id="exampleFormControlTextarea1" rows="3">
  </div>
  
  <div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Foto Bukti Masalah</label>
  <input type="file" class="" name="foto" id="exampleFormControlTextarea1" rows="3">
  </div>

  
  <button type="submit" class="btn btn-sm btn-warning mb-3 w-100">Submit</button>
</form>

</div>
    
</x-app-layout>

resources/views/daftarLaporan.blade.php
<x-app-layout class="">
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Selamat Datang di dashboard ') }}
        </h2>
    </x-slot>

    <div class="container">
     
      
      <table class="table bg-light mt-5 rounded shadow-lg table-light table-striped">
  <thead>
    <tr>
      <th scope="col">Tanggal </th>
      <th scope="col">Status</th>
      <th scope="col">Pengadu</th>
      <th scope="col">Isi Aduan</th>
      <th scope="col">Foto</th>
      <th scope="col"></th>
      
    </tr>
  </thead>
  
  <tbody>
    
      @foreach ($data as $item)
          <tr>
            <td class="">{{$item->tgl_pengaduan}}</td>        
            <td>
              @if($item->status === 'tunggu')
                <div class="btn-group"> 
                  <div class="btn btn-sm btn-outline-primary rounded-pill text-white fw-bold bg-danger" data-bs-toggle="dropdown" aria-expanded="false">{{$item->status}}</div>
                  </div>
             @endif
              @if($item->status === 'proses')
                <div class="btn-group"> 
                  <div class="btn btn-sm btn-outline-primary rounded-pill text-white fw-bold bg-info" data-bs-toggle="dropdown" aria-expanded="false">{{$item->status}}</div>
                  </div>
             @endif
              @if($item->status === 'selesai')
                <div class="btn-group"> 
                  <div class="btn btn-sm btn-outline-primary rounded-pill text-white fw-bold bg-success" data-bs-toggle="dropdown" aria-expanded="false">{{$item->status}}</div>
                  </div>
             @endif
            </td>
            <td>{{$item->nama_pengadu}}</td>
            <td>{{$item->isi_laporan}}</td>
            <td>
              @if ($item->foto)
              <img src="{{ Storage::url($item->foto) }}" height="75" width="75" alt="" />
              @endif
             </td>
            <td>
              <a href="{{url('tanggapan/'. $item->id_pengaduan)}}" class="btn btn-sm btn-success w-100 "  > Berikan Tanggapan  </a href="{{url('tanggapan/'. $item->id_pengaduan)}}">
                <div class="row mt-1">
                  <div class="col">
                    <form action="{{ url('proses/'. $item->id_pengaduan) }}" method="POST">
                      @csrf
                      @method('PUT')
                    <button type="submit" class="btn btn-sm btn-info text-warning fw-bold w-100" as="h6">Proses</button> 
                    </form>

                  </div>
                  <div class="col">
                  <form action="{{ url('selesai/'.  $item->id_pengaduan) }}" method="POST">
                    @csrf
                    @method('PUT')
                  <button class="btn w-25 btn-sm btn-warning text-success fw-bold w-100" type="submit" as="h6">Selesai</button>
                  </form>
                  </div>
                </div>
            </td>        
          </tr>
      @endforeach
     
    
  </tbody>
  </table>  

  @if(Auth::user()->role === 'administrator')
  <a class="btn btn-outline-success w-100" href="{{ URL::to('/admin/pdf') }}">Export to PDF</a>
  @endif

 
    
</x-app-layout>

<div class="modal fade" id="tanggapanmodal" tabindex="-1" aria-labelledby="tanggapanmodalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content border-0">
      <div class="modal-header bg-warning border-0">
        <h5 class="modal-title fw-bold " id="tanggapanmodalLabel">Beri Tanggapan</h5>
        <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form class="" >
    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nama Petugas</label>
    <input type="hidden" class="form-control rounded border-secondary border" value={{Auth::user()->id}} name="id" aria-describedby="emailHelp" disabled>
    <input type="text" class="form-control rounded border-secondary border" value={{Auth::user()->name}} name="name" aria-describedby="emailHelp" disabled>
    <div id="emailHelp" class="form-text"></div>
  

  <div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Berikan Tanggapan</label>
  <textarea class="form-control rounded border-secondary border" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>

  
  <button type="submit" class="btn btn-sm btn-warning mb-3 w-100">Submit</button>
</form>


      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary text-dark" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary text-dark">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

resources/views/dashboard.blade.php
<x-app-layout class="">
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Selamat Datang di dashboard Laporan Masyarakat Desa Komba') }}
        </h2>
    </x-slot>
    @if(Auth::user()->role === 'administrator')
    <div class="container">
        <div class="card text-center mt-3 shadow">
            <div class="card-body bg-warning">
              <img src="../../assets/img/lapor.svg" class="w-50 float-start" alt="">
              <span class="card-title fs-2 fw-bold text-white d-flex mt-5 pt-4">Halo {{Auth::user()->name}}</span>
              <span class="card-title fs-3 fw-bold align-right text-white d-flex">Mari lihat laporan Masyarakat</span>
              <span class="card-title fs-3 fw-bold align-right text-white d-flex">Akhir akhir ini</span>
              
            </div>
           
            <a href="daftarLaporan" class="btn btn-sm btn-success ">Lihat Laporan</a>
          </div>
    </div>
    @endif
    @if(Auth::user()->role === 'petugas')
    <div class="container">
      <div class="card text-center mt-3 shadow">
          <div class="card-body bg-warning">
            <img src="../../assets/img/lapor.svg" class="w-50 float-start" alt="">
            <span class="card-title fs-2 fw-bold text-white d-flex mt-5 pt-4">Halo {{Auth::user()->name}}</span>
            <span class="card-title fs-3 fw-bold align-right text-white d-flex">Mari lihat laporan Masyarakat</span>
            <span class="card-title fs-3 fw-bold align-right text-white d-flex">Akhir akhir ini</span>
            
          </div>
         
          <a href="daftarLaporan" class="btn btn-sm btn-success ">Lihat Laporan</a>
        </div>
  </div>
  @endif
  @if(Auth::user()->role === 'masyarakat')
  <div class="container">
    <div class="card text-center mt-3 shadow">
        <div class="card-body bg-warning">
          <img src="../../assets/img/buat.svg" class="w-25 float-start" alt="">
          <span class="card-title fs-2 fw-bold text-white d-flex mt-4 pt-4">Halo {{Auth::user()->name}}</span>
          <span class="card-title fs-3 fw-bold align-right text-white d-flex">Ayo buat laporan masalah di sekitarmu </span>
          <span class="card-title fs-3 fw-bold align-right text-white d-flex">Akhir akhir ini</span>
          
        </div>
       
        <a href="buatLaporan" class="btn btn-sm btn-success ">Buat Laporan</a>
      </div>
</div>
@endif

   
</x-app-layout>

resources/views/riwayatLaporan.blade.php
<x-app-layout class="">
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          Selamat Datang Di Dashboard
        </h2>
    </x-slot>

    <div class="container rounded bg-light  shadow-lg mt-3 mb-3" >
      

</div>

<div class="container">
  <div class="row">
    @foreach ($data as $item)
        
    <div class="card w-75 mt-4 bg-warning border-0 shadow-lg">
      <div class="">
        <span class="fw-bold ms-3 ">Laporanmu:</span>
        <br/>
        <span class="fw-normal ms-3 fs-6 me-3 text-white">"{{$item->isi_laporan}}"</span>
      </div>
      <div class="mt-2">
        <span class="fw-bold ms-3">Tanggapan Petugas:</span>
        <br/>
        @foreach ($datatanggapan as $value)
        <span class="fw-normal ms-3 fs-6  me-3 text-white">"{{$value->tanggapan}}"</span>
        @endforeach
      </div>
      <div class="mt-2"> 
        <span class="fw-bold ms-3 float-start">Status Laporan:</span>
        @if($item->status === 'tunggu')
        <span class="float-end rounded-pill badge bg-danger"> {{$item->status}} </span>
        @endif
        @if($item->status === 'proses')
        <span class="float-end rounded-pill badge bg-primary"> {{$item->status}} </span>
        @endif
        @if($item->status === 'selesai')
        <span class="float-end rounded-pill badge bg-success"> {{$item->status}} </span>
        @endif
      </div>
    </div>
    @endforeach
    </div>  
  </div>
</div>
    
</x-app-layout>

resources/views/tanggapan.blade.php
<x-app-layout class="">
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          Selamat Datang Di Dashboard
        </h2>
    </x-slot>

    <div class="container rounded bg-light  shadow-lg mt-3 mb-3" >
      
<form class="mt-5" method="POST" action="{{ route('tanggapan.store') }}" enctype="multipart/form-data">
  @csrf
  @method('POST')

  <input type="hidden" class="form-control rounded border-secondary border" name="id_tanggapan"  >
  <input type="hidden" class="form-control rounded border-secondary border" name="id_pengaduan" value={{$id}} id="exampleInputEmail1" >
  <input type="hidden" class="form-control rounded border-secondary border" name="id_petugas" value={{Auth::user()->id}} >

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nama Petugas</label>
    <input type="text" class="form-control rounded border-secondary border" name="nama_pengadu" value={{Auth::user()->name}} id="exampleInputEmail1" aria-describedby="emailHelp" disabled>
    {{-- <input type="hidden" class="form-control rounded border-secondary border" name="nik" value={{Auth::user()->nik}} id="exampleInputEmail1" aria-describedby="emailHelp" disabled> --}}
    <div id="emailHelp" class="form-text"></div>

    <input type="date" class="form-control rounded border-secondary border" name="tgl_tanggapan" id="exampleFormControlTextarea1" rows="3">
  <div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Berikan Tanggapan</label>
  <textarea class="form-control rounded border-secondary border" name="tanggapan" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>

  <button type="submit" class="btn btn-sm btn-warning mb-3 w-100">Submit</button>
</form>

</div>
    
</x-app-layout>